# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrvvQbZEohrUgdDPXpTTwu1k6TQOuVIA
"""

print("hello wolrd")

print("this is mesage")

print("fistline \n second message ")

num1 = 43; num2 = 4;

ans =  num1 + num2

print(ans)

ans = num1-num2

print(ans)

ans = num1*num2

print(ans)

ans = num1 / num2

print(ans)

ans = num1 // num2

print(ans)

textValue = input("Enter txt value ")

type(textValue)

numValue= int(input("Enter the number "))

type(numValue)

"""**CHALLENGES____001**

Q1  Ask for the user’s first name and display the output message Hello [First Name] .
"""

first_name = input("Enter the first name: ")
print("Hello",first_name)

""" Q2
 Ask for the user’s first name and then ask for their surname and display the output message Hello [First Name] [Surname].
"""

first_name = input("Enter the first name: ")
surname = input("Enter the first Surname: ")
print(first_name , surname)

"""Q3 : Write code that will display the joke “What do you call a bear with no teeth?” and on the next line display the answer “A gummy bear!” Try to create it using only one line of code."""

print("What do you call a bear with no teeth? \n A gummy bear!")

"""Q4 Ask the user to enter two numbers. Add them together and display the answer as The total is [answer]."""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter  second number: "))
answer = num1 + num2
print("The total is ", answer)

"""Q5 Ask the user to enter three numbers. Add together the first two numbers and then multiply this total by the third. Display the answer as The answer is [answer]."""

num1 = int(input("Enter first number: "))
num2 = int(input("Enter  second number : "))
num3 = int(input("Enter  second third: "))
answer = num1 + num2 +num3
print("The total is ", answer)

"""Q6  Ask how many slices of pizza the user started with and ask how many slices they have eaten. Work out how many slices they have left and display the answer in a user- friendly format.**bold text**"""

pizzaSlices = int(input(" how many slices of pizza the you started with ?"))
eatenSlices = int(input(" how many slices they have eaten ?"))
slicesLeft = pizzaSlices - eatenSlices
print("slices left",slicesLeft);

"""Q7 Ask the user for their name and their age. Add 1 to their age and display the output [Name] next birthday you will be [new age]."""

userName = input("Enter your name")
userAge = int(input("Enter your age"))
newAge = userAge +1;
print(f"{userName} next birthday you will be {newAge}")

"""Q8 Ask for the total price of the bill, then ask how many diners there are. Divide the total bill by the number of diners and show how much each person must pay."""

totalPrice = int(input("The total price of the bill ?"))
totalDiners = int(input("Number of Diners ?"))
eachPersonPay = totalPrice /totalDiners
print(f"each person must pay : {int(eachPersonPay)}")

"""Q9
Write a program that will ask for a number of days and then will show how many hours, minutes and seconds are in that number of days.

"""

numsOfDays = int(input("Number of days ?"))

hours = numsOfDays * 24
minutes = hours * 60
seconds = minutes * 60

print(f"In {numsOfDays} days there are:")
print(f"Hours: {hours}")
print(f"Minutes: {minutes}")
print(f"Seconds: {seconds}")

"""There are 2.204 pounds in a kilogram. Ask the
user to enter a weight in kilograms and convert it
to pounds.
"""

userWeight = float(input("Enter your weight ?"))
inPounds = userWeight*2.204;
print(f"your weight in pounds is : {inPounds}")

"""Q11
ask the user to enter a number over 100 and then enter a number under
10 and tell them how many times the smaller number goes into the larger
number in a user-friendly format.
"""

larger = int(input("Enter the number over 100 :"))
smaller = int(input("Enter the number under 10 :"))
ans =larger//smaller

print(f"{smaller}")

