# -*- coding: utf-8 -*-
"""condtionals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCnSA6XY4XzNSuID-DPmJfpNMt0w1kGb

Comparison
Operators
"""

10 == 10  #True (Equal to)

20 != 10 #True (Not equal to)

20>10 # True (Greater than)

10<20 #True (Less than)

10<=20 #True (Less than or equal to)

10>=20 #"False" (Greater than or equal to)

"""## Logical Operators

*   `and`: Returns `True` only if both operands are true. Example: `(5 > 3) and (4 < 7)` → `True`
*   `or`: Returns `True` if at least one operand is true. Example: `(5 < 3) or (4 < 7)` → `True`
*   `not`: Reverses the result (inverts `True` to `False` and vice versa).

If num1 is over 10, it will display the message “This is over 10”, otherwise it will check the next condition. If num1 is equal to 10, it will display the message “This is equal to 10”. Otherwise, if neither of the first two conditions have been met, it will display the message “This is under 10”.
"""

num = int(input("Enter the number: "))
if num == 10:
  print("This is equal than 10")
elif num >10:
  print("This is greater to 10")
else:
  print("This is less than 10")

"""If num1 is 10 or more then it will test another if statement to see if num1 is less than or
equal to 20. If it is, it will display the message “This is between 10 and 20”. If num1 is not
less than or equal to 20 then it will display the message “This is over 20”. If num1 is not
over 10, it will display the message “This is under 10”.
"""

num1 = int(input("ENTER THE NUMBER: "))

if num1 >=10:
  if num1 <=20:
    print("this number is between 10 and 20")
  else:
    print("this number is greater than 20")
else:
  print('this number is less than 10 ')

num1 = int(input("ENTER THE NUMBER between 10 and 20: "))
if num1 >=10 and num1 <=20:
  print("this number is between 10 and 20")
else:
    print("OUT OF RANGE ")

num = int(input("enter the even number between 1 and 5 "))
if num==4 or num==2:
   print("ACCEPETED ")
else:
   print("out of range")

"""Challenges

012
Ask for two numbers. If
the first one is larger
than the second, display
the second number first
and then the first
number, otherwise show
the first number first and
then the second
"""

num1 = int(input("Enter First Number"));
num2 = int(input("Enter Second Number"));

if num1>num2:
  print(num1,num2)
else:
  print(num2,num1)

"""013
Ask the user to enter a
number that is under
20. If they enter a
number that is 20 or
more, display the
message “Too high”,
otherwise display
“Thank you”.
"""

from types import new_class
num = int(input("Enter the number under 20 : "))

if num>=20:
  print("TOO HIGH")
else:
  print("Thankyou")

"""014
Ask the user to enter a
number between 10 and 20
(inclusive). If they enter a
number within this range,
display the message “Thank
you”, otherwise display the
message “Incorrect
answer
"""

num =int(input("Enter the Number between 10 and 20: "))

if num >=10 and num <=20 :
  print("Thankyou")
else:
  print('incorrect answer')

"""015
Ask the user to enter their favourite colour. If they enter “red”, “RED” or
“Red” display the message “I like red too”, otherwise display the message
“I don’t like [colour], I prefer red”
"""

