# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tO__bpiGHgO1u5edcTfXTWEsGzmju25i
"""

for i in range(1,10):
  print(i)

for i in range(1,10,2):
  print(i)

for i in range(10,1,-3):
  print(i)

txt = "nitesh"

for char in txt:
  print(char)

"""practice

035
Ask the user to enter
their name and then
display their name
three times.
"""

user_name = input("Enter your name : ")
for i in range(0,3):
  print(user_name,i)

"""036
Alter program 035 so that it will ask the user to enter their
name and a number and then display their name that
number of times.
"
"""

user_name = input("Enter your name : ")
n = int(input("Enter the number : "))

for i in range(0,n):
  print(user_name,i)

"""37
Ask the user to enter their name and display each letter in
their name on a separate line.
"""

for i in user_name:
  print(i)

"""38
Change program
037 to also ask for a
number. Display
their name (one
letter at a time on
each line) and
repeat this for the
number of times
they entered.
"""

n = int(input("enter n : "))

for i in range(0,n):
  for char in user_name:
    print(char)

"""39
Ask the user to enter a number between 1
and 12 and then display the times table for
that number.
"""

n = int(input("enter n :"))

for iz in range(1,n+1):
  for i in range (1,11):
    print(f"{iz} x {i} = {i*iz}")
  print(" ")

"""40
Ask for a number below 50 and then count down from
50 to that number, making sure you show the number
they entered in the output.
"""

num = int(input("enter num below 50 :"))
if num <50:
  for i in range(50,num-1,-1):
    print(i)
else:
  print("re enTER THE NUMBER ")

"""41
Ask the user to enter their
name and a number. If the
number is less than 10, then
display their name that
number of times; otherwise
display the message “Too
high” three times
"""

name = input("Enter your name: ")
number = int(input("Enter a number: "))

if number < 10:
    for _ in range(number):
        print(name)
elif number >= 10:
    for _ in range(3):
        print("Too high")

"""42
Set a variable called total to 0. Ask the user to enter
five numbers and after each input ask them if they
want that number included. If they do, then add the
number to the total. If they do not want it included,
don’t add it to the total. After they have entered all five
numbers, display the total
"""

total = 0

for i in range(5):
    num = int(input(f"Enter number {i+1}: "))
    include = input("Do you want to include this number? (yes/no): ").lower()
    if include == 'yes':
        total += num

print(f"The total is: {total}")3

"""043
Ask which direction the user wants to count (up or down). If they select up, then ask
them for the top number and then count from 1 to that number. If they select down, ask
them to enter a number below 20 and then count down from 20 to that number. If they
entered something other than up or down, display the message “I don’t understand”
"""

direction = input("Do you want to count up or down? ").lower()

if direction == 'up':
    top_number = int(input("Enter the top number: "))
    for i in range(1, top_number + 1):
        print(i)
elif direction == 'down':
    bottom_number = int(input("Enter a number below 20: "))
    if bottom_number < 20:
        for i in range(20, bottom_number - 1, -1):
            print(i)
    else:
        print("Number must be below 20.")
else:
    print("I don't understand")

"""044
Ask how many people the user wants to invite to a party. If they enter a number below
10, ask for the names and after each name display “[name] has been invited”. If they
enter a number which is 10 or higher, display the message “Too many people
"""

num_people = int(input("How many people do you want to invite to the party? "))

if num_people < 10:
    for i in range(num_people):
        name = input(f"Enter the name of person {i+1}: ")
        print(f"{name} has been invited")
else:
    print("Too many people")