# -*- coding: utf-8 -*-
"""maths.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRA8Bvo6qOQGgQNiqCdmdhB3B3HN49Kb
"""

import math

math.pi

math.e

math.factorial(4)

math.pow(3,2)

a = 2.3
print ("The ceil of 2.3 is : ", end="")
print (math.ceil(a))
print ("The floor of 2.3 is : ", end="")
print (math.floor(a))

a = 15
b = 5
print ("The gcd of 5 and 15 is : ", end="")
print (math.gcd(b, a))

print ("The value of log 2 with base 3 is : ", end="")
print (math.log(2,3))
print ("The value of log2 of 16 is : ", end="")
print (math.log2(16))
print ("The value of log10 of 10000 is : ", end="")
print (math.log10(10000))

"""### Program 027: Multiply a decimal number by two"""

num = float(input("Enter a number with lots of decimal places: "))
result = num * 2
print(f"The answer is: {result}")

"""### Program 028: Display the answer to two decimal places"""

num = float(input("Enter a number with lots of decimal places: "))
result = num * 2
print(f"The answer to two decimal places is: {result:.2f}")

"""### Program 029: Calculate square root of a number over 500"""

while True:
    try:
        num = int(input("Enter an integer that is over 500: "))
        if num > 500:
            break
        else:
            print("Number must be greater than 500. Please try again.")
    except ValueError:
        print("Invalid input. Please enter an integer.")

sqrt_num = math.sqrt(num)
print(f"The square root of {num} is: {sqrt_num:.2f}")

"""### Program 030: Display pi (π) to five decimal places"""

print(f"Pi (π) to five decimal places is: {math.pi:.5f}")

"""### Program 031: Area of a circle"""

while True:
    try:
        radius = float(input("Enter the radius of the circle: "))
        if radius >= 0:
            break
        else:
            print("Radius cannot be negative. Please try again.")
    except ValueError:
        print("Invalid input. Please enter a number.")

area = math.pi * (radius ** 2)
print(f"The area of the circle is: {area:.2f}")

"""### Program 032: Volume of a cylinder"""

while True:
    try:
        radius = float(input("Enter the radius of the cylinder: "))
        depth = float(input("Enter the depth of the cylinder: "))
        if radius >= 0 and depth >= 0:
            break
        else:
            print("Radius and depth cannot be negative. Please try again.")
    except ValueError:
        print("Invalid input. Please enter numbers.")

circle_area = math.pi * (radius ** 2)
volume = circle_area * depth
print(f"The total volume of the cylinder is: {volume:.3f}")

"""### Program 033: Whole number division and remainder"""

while True:
    try:
        num1 = int(input("Enter the first number: "))
        num2 = int(input("Enter the second number: "))
        if num2 == 0:
            print("Cannot divide by zero. Please enter a non-zero second number.")
        else:
            break
    except ValueError:
        print("Invalid input. Please enter integers.")

division_result = num1 // num2
remainder = num1 % num2
print(f"{num1} divided by {num2} is {division_result} with {remainder} remaining.")

"""### Program 034: Area of square or triangle"""

print("Choose an option:")
print("1. Calculate the area of a square")
print("2. Calculate the area of a triangle")

while True:
    try:
        choice = input("Enter your choice (1 or 2): ")
        if choice == '1':
            side = float(input("Enter the length of one side of the square: "))
            area = side ** 2
            print(f"The area of the square is: {area:.2f}")
            break
        elif choice == '2':
            base = float(input("Enter the base of the triangle: "))
            height = float(input("Enter the height of the triangle: "))
            area = 0.5 * base * height
            print(f"The area of the triangle is: {area:.2f}")
            break
        else:
            print("Invalid choice. Please enter 1 or 2.")
    except ValueError:
        print("Invalid input. Please enter a number for dimensions.")